### ISSUE TITLE
scala.Tuple2 doesn't exist

### ISSUE THREAD

**Issue by lopezavila69** [deanwampler/prog-scala-2nd-ed-code-examples#14]
Hello,

I have downloaded the code examples, SBT 0.13.9 and Scala 2.11.6. Both of them have been installed separately in a Windows 10 machine. After downloading the dependencies, which seem to be correct I get these errors:

```
C:\home\aall\projects\scala-examples>sbt test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from C:\home\aall\projects\scala-examples\project
[info] Set current project to Programming Scala, Second Edition - Code examples (in build file:/C:/home/aall/projects/scala-examples/)
[info] Compiling 70 Scala sources and 4 Java sources to C:\home\aall\projects\scala-examples\target\scala-2.11\classes...
[error] C:\home\aall\projects\scala-examples\src\main\java\progscala2\javainterop\ScalaTuples.java:3: error: package scala does not exist
[error] import scala.Tuple2;
[error]             ^
[error] C:\home\aall\projects\scala-examples\src\main\java\progscala2\javainterop\ScalaTuples.java:7: error: cannot find symbol
[error]     Tuple2<String,Integer> stringInteger = new Tuple2<String,Integer>("one", 2);
[error]     ^
[error]   symbol:   class Tuple2
[error]   location: class ScalaTuples
[error] C:\home\aall\projects\scala-examples\src\main\java\progscala2\javainterop\ScalaTuples.java:7: error: cannot find symbol
[error]     Tuple2<String,Integer> stringInteger = new Tuple2<String,Integer>("one", 2);
[error]                                                ^
[error]   symbol:   class Tuple2
[error]   location: class ScalaTuples
[error] 3 errors
[error] (compile:compile) javac returned nonzero exit code
[error] Total time: 16 s, completed 04-ene-2016 23:15:37
```

It cannot find scala.Tuple2 class... At least in the latest API docs  (Scala 2.11.7) the class appears:

http://www.scala-lang.org/api/current/index.html#scala.Tuple2

After this, I uninstalled the separated Scala package and removed `.sbt` and `.ivy2` in my Windows home directory. Furthermore, I rebooted the system and executed `sbt test` again...the result was the same.

Maybe I have a problem with my home folder: `C:\Users\Álvaro\.ivy2`  (note the Á)
What can I do?

 Thanks in advance.

**Comment by deanwampler** [comment]
I successfully ran a clean build on Windows 8 (in VMWare, full disclosure...). Your issue probably indicates a corrupt `%HOME%/.ivy2/` repo (where the downloaded dependencies go ... to die?? ;) This can happen if the Maven `.pom` files are there, but not the `.jar` files, for some reason.

You could try deleting the whole `%HOME%/.ivy2/` directory, but it will force downloading all dependencies again, including for any other project you have that uses a build tool like SBT that uses Ivy2 for dependencies. You might first try deleting `%HOME%/.ivy2/cache/org.scala-lang` and see if that's enough.

**Comment by lopezavila69** [comment]
Hello Dean,

I have removed just that folder, but I have not solved the problem.

In some of the folders, some older jars are appearing, is it ok? For instance, in scala-library\jars I have stored two versions:

`
scala-library-2.10.4.jar
scala-library-2.11.6.jar
`

The same is happening in other folders, and in jline and scalap I haven't the correspoding 2.11.6 version...maybe the dependencies are not fully resolved correctly.

Any idea? Thanks.

**Comment by deanwampler** [comment]
Those look right. Make sure they aren't zero size. The `TupleN` classes are
in the `scala-library` jar. The next thing I would try is rename
`%HOME%/.ivy2`, so SBT creates a new version, and see if that fixes it.

**Comment by lopezavila69** [comment]
Your latest update made it possible (Scala 2.11.7 dependencies) !!! I removed again the '.ivy2' and '.sbt' folders under my home folder:

`[info] Passed: Total 37, Failed 0, Errors 0, Passed 37`
`[success] Total time: 263 s, completed 07-ene-2016 22:49:14`

Thank you so much ;)

**Comment by deanwampler** [comment]
Glad you got it working.
