### ISSUE TITLE
invariant example is giving errors in IntelliJ

### ISSUE THREAD

**Issue by JohnReedLOL** [deanwampler/prog-scala-2nd-ed-code-examples#17]
In IntelliJ, I am getting this:

http://i.imgur.com/ZBqT6HK.png?1

I also had to ask this question:

http://stackoverflow.com/questions/36118298/scala-quasiquote-macro-example-broken

Is IntelliJ just stupid?

**Comment by JohnReedLOL** [comment]
[info] Compiling 2 Scala sources to /home/johnreed/sbtProjects/scala-trace-debug/target/scala-2.11/test-classes...
[error] /home/johnreed/sbtProjects/scala-trace-debug/src/test/scala/mataprogramming/invariant2.scala:30: type mismatch;
[error]  found   : TreeNode
[error]     (which expands to)  scala.reflect.api.Trees#Tree
[error]  required: context.universe.Tree
[error]         val exceptionMessage = s"FAILURE! $predicateAsString == false, for statement: " + showCode(statement)

There's something really funky with the types. Either IntelliJ is messing up the types or the notion escapes me.

**Comment by deanwampler** [comment]
It appears to compile okay for me on IntelliJ 14 community edition, where I imported the SBT project so it's using Scala 2.11.7. I get different highlight warnings than you do. They appear to be bogus.

**Comment by JohnReedLOL** [comment]
Thank you. Side note, in the macro example, why do you do flatMap and not just map.

For example...

```
// src/main/scala/progscala2/metaprogramming/invariant2.scala
package metaprogramming

import scala.language.experimental.macros
import scala.reflect.api.Trees

import scala.reflect.macros.blackbox.Context

/**
  * A Macro written using the current macro syntax along with quasiquotes.
  * Requires a predicate for an invariant to be true before each expression
  * is evaluated.
  */
object invariant2 {

  def execute[T](predicate: => Boolean)(block: => T): T = macro executeMacro
  def executeMacro(context: Context)(predicate: context.Tree)(block: context.Tree) = {
    import context.universe._
    val predicateAsString = showCode(predicate)

    type SyntaxTree = context.Tree

    val q"..$stmts" = block
    val statements: Seq[SyntaxTree] = stmts
    val statementsWithInvariants: Seq[SyntaxTree] = statements.map{ (statement: SyntaxTree) =>
      // showCode requires "context.universe.Tree"
      val exceptionMessage =
          s" FAILURE! $predicateAsString == false, for statement: " + showCode(statement)
      val throwStatement: SyntaxTree =
          q" throw new metaprogramming.invariant.InvariantFailure($exceptionMessage) "
      val predicateStatement: SyntaxTree =
          q" if (false == $predicate) $throwStatement "
      q" { $predicateStatement; $statement }; "
    }
    val initialThrowStatement: SyntaxTree =
        q"throw new metaprogramming.invariant.InvariantFailure($predicateAsString)"
    val initialPredicateStatement: SyntaxTree =
        q"if (false == $predicate) $initialThrowStatement"
    q"$initialPredicateStatement; ..$statementsWithInvariants"
  }

  case class InvariantFailure(msg: String) extends RuntimeException(msg)
}
```

^ Is there any extra benefit in using statements.flatMap instead of statements.map?

Side note: I'm trying to use this feature to add to my library: 

https://github.com/JohnReedLOL/debugtrace/

**Comment by deanwampler** [comment]
Since this is 2 years old, I'm going to close it, but please reopen it or open a new ticket if newer IntelliJ versions still cause problems. Thanks.
