### ISSUE TITLE
compilation errors in eclipse

### ISSUE THREAD

**Issue by beep02** [deanwampler/prog-scala-2nd-ed-code-examples#2]
sbt ran OK.

my eclipse-lune ide (scala 2.11.4) (Java 8), had an error in the test SMapTest.java (package declaration is wrong).

But I also have errors are in metaprogramming package, something about macros.

So I deleted the package meanwhile (and it's tests).

Thanks.

**Comment by deanwampler** [comment]
Thanks for reporting your issues. I had no trouble compiling the metaprogramming examples with Scala-IDE 4.0 final. I fixed the package error with SMapTest.java and a few other warnings surfaced by Eclipse. I've pushed these changes.

**Comment by beep02** [comment]
Thank you.
I think metaprogramming  is working. Some glitch.
