### ISSUE TITLE
"A Taste of Concurrency", first example

### ISSUE THREAD

**Issue by giacecco** [deanwampler/prog-scala-2nd-ed-code-examples#20]
In the book (PDF version bought and downloaded from O'Reilly on Aug 5th 2016) the source for the first code example in "A Taste of Concurrency" section of chapter 1 shows as its first line:

```// src/main/scala/progscala2/introscala/shapes/Shapes.scala```

but the file in this repository is called ```shapes.scala```, with a lowercase 's'.

**Comment by deanwampler** [comment]
Thanks for taking the time to report this, but for errors in the book, like this typo, please report them here: http://www.oreilly.com/catalog/errata.csp?isbn=0636920033073.
