### ISSUE TITLE
how to run code?

### ISSUE THREAD

**Issue by anonygrits** [deanwampler/prog-scala-2nd-ed-code-examples#7]
I am trying to run the shapes code, but I can't figure out where to start sbt. If I start it at the book folder level, then sbt can't find the shapes code (it only sees the first level scripts). If I go all the way down to the shapes folder, then it can't find all the imports for akka. Can you please clarify? Thx!

**Comment by deanwampler** [comment]
Page 29 in the book explains how to run it.

**Comment by anonygrits** [comment]
Actually, I don't think it does, but thanks anyway. I'll try some other
scala books.
